### PR TITLE
stand alone feedback form in docs

### PR DESCRIPTION
**Pull request by SBBCornell**
When testing locally the form doesnt display. Let me know if you think its a markdown conflict or something else.

### CODE REVIEW

**Comment by mhl10** [comment]
> When testing locally the form doesnt display. Let me know if you think its a markdown conflict or something else.

This appears to be a problem with CORS in that the javascript is pulling from atlassian.net; recent updates to browsers like Chrome recently strengthened enforcement of cross-origin requests and I think this will affect all of our feedback forms and not just this one. I'll see if I can find a fix for this.

**Comment by mhl10** [comment]
> > When testing locally the form doesnt display. Let me know if you think its a markdown conflict or something else.
> 
> This appears to be a problem with CORS in that the javascript is pulling from atlassian.net; recent updates to browsers like Chrome recently strengthened enforcement of cross-origin requests and I think this will affect all of our feedback forms and not just this one. I'll see if I can find a fix for this.

I may be incorrect in my original thinking about the cause. I'll have to investigate further.

**Comment by SBBCornell** [comment]
quick update: found out that Jira's form code cant be embedded inline. I have it working with a trigger button, but am looking into ways to embedd a simple form.

**Comment by SBBCornell** [comment]
quick update: found out that Jira's form code cant be embedded inline. I have it working with a trigger button, but am looking into ways to embedd a simple form.

**Pull request closed without merging**
