### PR TITLE
Updates http links to https

### PR DESCRIPTION
**Pull request by jweiskoff**
Updates all http links and other mentions to https

### CODE REVIEW

**Review by alisonhofer — APPROVED** [review]

**Comment by alisonhofer** [comment]
Looks good!

**Review by jonathanhyoung — APPROVED** [review]
If you just write "//arxiv.org/..." you will get links which work on both http and https pages.  Do we need to worry about our Chinese users who can't access us via https?

**Comment by jweiskoff** [comment]
The last question isn't in scope for this PR, but it'd be good to update the documentation, since everything in the main site is forcibly redirected anyway. 
The problem is that `export.` doesn't require SSL (I think for historical purposes, but also I don't know that our apis support ssl either).

**Review by cbf66 — COMMENTED** [review]
It's most likely not correct to change all the `http` references in `xmlns` attributes, or `schema=` attributes. These are URIs, not meant to really be used as URLs, but rather simply strings that identify the namespace or schema.

**Pull request merged**
