### PR TITLE
Pre-release merge for docs 0.6.5

### PR DESCRIPTION
**Pull request by bmaltzan**

### CODE REVIEW

**Review by afromme — APPROVED** [review]
looks good

**Review by jimentwood — APPROVED** [review]
looks good

**Review by jweiskoff — APPROVED** [review]
g2g

**Review by SBBCornell — APPROVED** [review]
the change I made looks as expected. thumbs up.

**Review by afromme — APPROVED** [review]
looks good

**Review by mhl10 — APPROVED** [review]
Looks good!

**Comment by bmaltzan** [comment]
In mistakes.md, changed:  pacakge's -> package's

**Pull request merged**
