### PR TITLE
Mention where paper passwords can be found

### LINKED ISSUE #617: arXiv documentation does not mention where a paper password can be recovered from
**Is your feature request related to a problem? Please describe.**

Currently, neither the Passwords documentation page ([link](https://info.arxiv.org/help/passwords.html)) or the Authority records page ([link](https://info.arxiv.org/help/authority.html)) mention, where exactly a paper password can be recovered from. I just had to go to Google and StackExchange (specifically a comment by LudvigH of [this answer](https://academia.stackexchange.com/a/54814)) to find this out, so I could instruct a submitting author where they could find it.

**Describe the solution you'd like**

A short mention on both the Password and Authority records pages regarding where a paper password can be found, once a paper has been submitted. Currently a paper password is received in the confirmation e-mail of a submitted article.

**Describe alternatives you've considered**

There really are no better alternatives. This is very simple to implement, not very time consuming and the best option in terms of accessibility. I don't think anyone wants to spend the time to make a video on this?

**Additional context**

Some authors are not aware of the possibility of linking the arXiv accounts of other authors to a paper, so they do not pay attention to the part of the e-mail that tells the paper password, when it is first received. This is how I ended up looking for this information.

### PR DESCRIPTION
**Pull request by SeSodesa**
This was done on the following pages:

- source/help/authority.md
- source/help/passwords.md

Closes #617.

### CODE REVIEW

**Review by cbf66 — COMMENTED** [review]
While I realize that eliminating trailing spaces at the ends of lines is good form, even in Markdown, it kind of pollutes the git change history, making it harder to pick out your substantiative changes.

@jweiskoff -- what do you think?

Also the change to this sentence:

> When a paper is first submitted to arXiv,
the submitter is the one and only owner of the paper, and receives a **paper
password** in the confirmation e-mail related to the paper submission, *if*
they marked themselves as an author during the submission phase.

nearly makes it a run-on sentence. arXiv has many users to are not native English speakers. Is there a way to break this up so it's easier to parse?

Otherwise, thanks for making this a PR!
>

**Comment by jweiskoff** [comment]
There's some deliberateness to not explaining paper passwords on the authority page because the purpose of the page is about authority records (and general authority to submit). I'm also not a fan of unneeded emphasis. I'll clean it up a bit, to sound more like the rest of the page.

**Comment by jweiskoff** [comment]
This will be closed in favor of #619. For some odd reason github isn't sending my commits to this PR. ¯\_(ツ)_/¯

**Comment by SeSodesa** [comment]
> While I realize that eliminating trailing spaces at the ends of lines is good form, even in Markdown, it kind of pollutes the git change history, making it harder to pick out your substantive changes.
> 
> @jweiskoff -- what do you think?
> 
> Also the change to this sentence:
> 
> > When a paper is first submitted to arXiv,
> the submitter is the one and only owner of the paper, and receives a **paper
> password** in the confirmation e-mail related to the paper submission, *if*
> they marked themselves as an author during the submission phase.
> 
> nearly makes it a run-on sentence. arXiv has many users to are not native English speakers. Is there a way to break this up so it's easier to parse?
> 
> Otherwise, thanks for making this a PR!
> > 
> 

I did think the sentence was a bit long when writing it, but went with it anyways. Thanks for considering the PR.

**Comment by SeSodesa** [comment]
> This will be closed in favor of #619. For some odd reason github isn't sending my commits to this PR. ¯\_(ツ)_/¯ 

I'm pretty sure I had "Allow maintainers to make edits" ticked, but oh well. ¯\_(ツ)_/¯

**Pull request closed without merging**
