### PR TITLE
ARXIVNG-2034 add NG-specific metadata help page

### PR DESCRIPTION
**Pull request by eawoods**
Some of the information on the help page for metadata (arxiv.org/help/prep) is incorrect for NG.
This page attempts to modify the prep instructions to be accurate for NG submission. I also removed almost all instances of the word "should" in place of more informative phrasing. 

Unfortunately it's a clone of the prep page and a lot of content is duplicated. Not sure how to avoid that in the short term, in order to apply the "NG metadata fields are Unicode friendly" aspect of metadata help. Maybe /help/prep could be edited with NG-specific sections instead?  Open for suggestions on making this a better fit for longer term support. I think this page needs to exist to support NG submission alpha, but defer to the judgement of others.

### CODE REVIEW

**Comment by jimentwood** [comment]
I had held off on this to brainstorm ideas for how we approach this for clarity.
Would one metadata page with a table for legacy/NG be easier to navigate than 2 different metadata pages?
How drastic are the differences between systems?

In our user support also we need to direct users to metadata format requirements multiple times a day. Typically through canned msgs


________________________________

**Comment by SBBCornell** [comment]
@jimentwood and @mhl10, I want to get a useful to-do item on my list for this ticket but realize that I need a little more background. If either of you have a moment a quick walk through would be great.

**Comment by SBBCornell** [comment]
> @jimentwood and @mhl10, I want to get a useful to-do item on my list for this ticket but realize that I need a little more background. If either of you have a moment a quick walk through would be great.

I spoke with Jim and have clarity. We'll create a ticket pegged to the beta release of submission ui to track and make necessary updates to the help section.

**Comment by SBBCornell** [comment]
Track relevant progress here: https://arxiv-org.atlassian.net/browse/ARXIVNG-2034

**Pull request closed without merging**
