### PR TITLE
Pre-release merge for docs 1.0.3

### PR DESCRIPTION
**Pull request by bmaltzan**

### CODE REVIEW

**Review by jweiskoff — APPROVED** [review]

**Review by jimentwood — APPROVED** [review]
looks good

**Review by jweiskoff — COMMENTED** [review]
@bmaltzan can you confirm that I did this correctly? I used a different redirect as a template, but I don't know for sure if there's db/site changes required when this is merged.

**Comment by bmaltzan** [comment]
@jweiskoff Yep, perfect!

**Comment by bmaltzan** [comment]
@afromme In /about/membership, is it ok that I bumped the year 2020->2021:? 
"find your institution's overall submission rank](https://arxiv.org/about/reports/2020_institution_submissions).

**Comment by jweiskoff** [comment]
> @afromme In /about/membership, is it ok that I bumped the year 2020->2021:?
> "find your institution's overall submission rank](https://arxiv.org/about/reports/2020_institution_submissions).

I think she's on vacation, but probably fine.

**Pull request merged**
