### PR TITLE
(WIP) Various fixes to mkdocs

### PR DESCRIPTION
**Pull request by SBBCornell**
A PR to fix various things in mkdocs, including typos and other minor changes.

Of note is the inclusion of the literate-nav plugin, which lets us specify the top level sidebar the way Charles requested, but still infer the subdirectory navigation:
Screen Shot 2022-12-02 at 12 00 22 PM

### CODE REVIEW

**Comment by SBBCornell** [comment]
Note: the nested nav generated by the Material theme are not keyboard navigable/accessible. There is no mechanism for opening the nested element via keyboard. We should discuss.

**Review by cbf66 — APPROVED** [review]
This looks good. But note that this plug-in doesn't actually add any capabilities to the MKDocs navigation column -- it just moves the description of the nav bar from the mkdocs.yml file into a Markdown file. I'm kind of indifferent to this, since both are fully under our control.

Hmm. but it also puts each folder's navigation information into that folder. I think on the whole, I like that approach, as it decentralizes the nav -- we won't have everyone modifying mkdocs.yml, so ➕**1** (edited) 

Let's merge this and see what it looks like live. But I think this is just the first step -- now we figure out what the right top-level navigation looks like, and perhaps also combine that we re-arranging the lower directories so the clustering makes sense.

**Comment by cbf66** [comment]
@bdc34 -- can you take care of the cloud build failure? 

>  ERROR    -  Config value: 'plugins'. Error: The "literate-nav" plugin is not installed

See [https://github.com/oprypin/mkdocs-literate-nav]() -- for the pip install command.

**Comment by bdc34** [comment]
> @bdc34 -- can you take care of the cloud build failure?
> 
> > ERROR    -  Config value: 'plugins'. Error: The "literate-nav" plugin is not installed
> 
> See https://github.com/oprypin/mkdocs-literate-nav -- for the pip install command.

I'll take a look.

**Comment by bdc34** [comment]
@cbf66 That's fixed. It is added to mkdocs-requirements.txt

**Review by bdc34 — APPROVED** [review]

**Pull request merged**
