### PR TITLE
Pre-release merge for docs 0.9.0

### PR DESCRIPTION
**Pull request by bmaltzan**

### CODE REVIEW

**Review by jweiskoff — APPROVED** [review]
Good to go.

**Review by afromme — APPROVED** [review]
looks good

**Review by SBBCornell — APPROVED** [review]
looks good!

**Review by mhl10 — APPROVED** [review]

**Review by jimentwood — APPROVED** [review]

**Review by helendwang — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
