### PR TITLE
change /help/statistics path to /help/stat

### PR DESCRIPTION
**Pull request by kyokukou**
archive keys are used for links, the key for the statistics archive is stat

### CODE REVIEW

**Comment by jimentwood** [comment]
The information about the statistics group should be disambiguated from pages about arXiv usage statistics. 
A url for /help/stats has been associated with usage statistics.
A url for /help/statistics has been associated with the statistics group
Based on that we may not want to make the changes proposed in this PR

**Comment by jimentwood** [comment]
I would like to chat and consider a custom url for statistics on the home page. We had custom urls for those links in the past.
Some notes at
https://arxiv.slack.com/archives/CFHF8SW79/p1709069892867779

From: Erin ***@***.***>
Date: Wednesday, February 28, 2024 at 9:41 AM
To: arXiv/arxiv-docs ***@***.***>
Cc: Jim Entwood ***@***.***>, Review requested ***@***.***>
Subject: Re: [arXiv/arxiv-docs] change /help/statistics path to /help/stat (PR #812)

Statistics is easier for humans to read but creates consistency problems with the rest of our url naming schemes. pages like https://arxiv.org/archive/stat or https://info.arxiv.org/help/q-bio/ all use archives tags. This creates problems like the broken link on the home page because the urls are all generated systematically.

**Comment by bdc34** [comment]
> I would like to chat and consider a custom url for statistics on the home page. We had custom urls for those links in the past. Some notes at https://arxiv.slack.com/archives/CFHF8SW79/p1709069892867779 

One option would be to use /help/stats for help about the archive for consistency with a redirect from /help/statistics to that. And then have a URL that is much more unambiguous for the arxiv site usage. /help/usage_data or something like that.

**Comment by jimentwood** [comment]
True that is an option.

My first assumption was that was more work overall, with more user impacted changes, than adding a conditional to the home page, like what we used to have for corr.

From: Brian Caruso ***@***.***>
Date: Wednesday, February 28, 2024 at 10:12 AM
To: arXiv/arxiv-docs ***@***.***>
Cc: Jim Entwood ***@***.***>, Review requested ***@***.***>
Subject: Re: [arXiv/arxiv-docs] change /help/statistics path to /help/stat (PR #812)

I would like to chat and consider a custom url for statistics on the home page. We had custom urls for those links in the past. Some notes at https://arxiv.slack.com/archives/CFHF8SW79/p1709069892867779

One option would be to use /help/stats for help about the archive for consistency with a redirect from /help/statistics to that. And then have a URL that is much more unambiguous for the arxiv site usage. /help/usage_data or something like that.

**Comment by kyokukou** [comment]
I like Brian's option. Having the statistics arxiv at /stat means no special conditional on the homepage or anywhere else that might apply. Moving /stats to something else is a bit more work, but moving to a better long term system. I believe we would be able to put in a redirect from /stats to whatever the usage statistics new home is to avoid impacting users

**Pull request closed without merging**
