### PR TITLE
Pre-release merge for docs 0.7.7

### PR DESCRIPTION
**Pull request by bmaltzan**

### CODE REVIEW

**Review by mhl10 — APPROVED** [review]
Looks good! Static assets (PDFs) will have to be pushed to the CDN as part of the deployment.

**Review by jweiskoff — APPROVED** [review]
g2g

**Review by jimentwood — APPROVED** [review]
looks good

**Review by afromme — APPROVED** [review]
looks good

**Review by SBBCornell — APPROVED** [review]
looks great!

**Pull request merged**
